name: 'TurboRepo with github artifacts'
description: 'Setup up a local cache proxy server for TurboRepo.'
author: 'felixmosh'
branding:
  icon: 'chevrons-up'
  color: 'yellow'

inputs:
  repo-token:
    description: 'An access token with repo permission'
    required: true
  server-token:
    description: 'An access token of the local turbo-server'
    required: false

runs:
  using: 'node16'
  main: 'dist/starter/index.js'
  post: 'dist/post/index.js'
